Fix push_to_github CI job failing due to shallow GIT_DEPTH

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -136,9 +136,17 @@ push_to_github:
   image:
     name: alpine/git:latest
     entrypoint: [""]
+  variables:
+    GIT_DEPTH: 0
   rules:
     - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
   script:
+    - git fetch origin main
+    - |
+      if ! git merge-base --is-ancestor "$CI_COMMIT_SHA" origin/main; then
+        echo "ERROR: tag $CI_COMMIT_TAG ($CI_COMMIT_SHA) is not on main. Release tags must be created from main (after merge)." >&2
+        exit 1
+      fi
     - git remote add github https://oauth2:${GITHUB_MIRROR_TOKEN}@github.com/simplito/deepfellow-infra.git
     - git push github HEAD:refs/heads/main
     - git push github $CI_COMMIT_TAG
